# Numpy for beginners
> From Alex Lu with Love
- toc: true
- title: Intro to Numpy
- author: Alex Lu
- badges: true
- comments: true
- categories: [jupyter,interests]

## NumPy

NumPy is the fundamental package for scientific computing with Python.

At the core of the NumPy package, is the `ndarray` object or n-dimensional array. In programming, array describes a collection of elements, similar to a list. The word n-dimensional refers to the fact that ndarrays can have one or more dimensions. 

Here I will directly convert a list to an ndarray using the `numpy.array()` constructor. To create a 1D ndarray, I can pass in a single list

In [ ]:
import numpy as np #using the alias np
array_data = np.array([1,2,3,4])

In [ ]:
print(array_data)
print(type(array_data))

[1 2 3 4]
<class 'numpy.ndarray'>


It's often useful to know the number of rows and columns in a ndarray. I can use the `ndarray.shape` attribute. 


In [ ]:
array_2D = np.array([[5, 10, 15],
                    [20, 25, 30]])
print(array_2D.shape) 


(2, 3)


### Vectorization in NumPy
The NumPy library takes advantage of a processor feature called *Single Instruction Multiple Data (SIMD)* to process data faster. SIMD allows a processor to perform the same operation on multiple data points in a single processor cycle.

The concept of replacing for loops with operations applied to multiple data points at once is called **vectorization**, and ndarrays make vectorization possible.

In [ ]:
numbers = [[6, 5], [1, 3], [5, 6], [1, 4], [3, 7], [5, 8], [3, 5], [8, 4]]
print(*numbers, sep='\n')

[6, 5]
[1, 3]
[5, 6]
[1, 4]
[3, 7]
[5, 8]
[3, 5]
[8, 4]


In [ ]:
# Python for loops implementation
sums = []
for row in numbers:
  row_sum = row[0] + row[1]
  sums.append(row_sum)

print(sums)

[11, 4, 11, 5, 10, 13, 8, 12]


In [ ]:
# NumPy
# Convert the list of lists to an ndarray
np_numbers = np.array(numbers)
sums = np_numbers[:,0] + np_numbers[:,1]
print(sums)


[11  4 11  5 10 13  8 12]


When I selected each column, we used the syntax `ndarray[:,c]` where c is the column index I wanted to select. The colon selects all rows.

In [ ]:
# Select one or more data in ndarray
#print(np_numbers)
#print(np_numbers[1])
#print(np_numbers[2:])

#print(np_numbers[3,1])
#print(np_numbers[:,1])

# Select specific row
rows = [0, 2, 4]
print(np_numbers[rows, :])

[[6 5]
 [5 6]
 [3 7]]


### Explore the numerical dataset
To explore two-dimensional (2D) ndarrays, I'll analyze New York City taxi trip data released by the city of New York.

In [ ]:
!wget -nc /content/ https://datasets21.s3-us-west-1.amazonaws.com/nyc_taxis.csv

/content/: Scheme missing.
File ‘nyc_taxis.csv’ already there; not retrieving.



In [ ]:
!wget --help

GNU Wget 1.19.4, a non-interactive network retriever.
Usage: wget [OPTION]... [URL]...

Mandatory arguments to long options are mandatory for short options too.

Startup:
  -V,  --version                   display the version of Wget and exit
  -h,  --help                      print this help
  -b,  --background                go to background after startup
  -e,  --execute=COMMAND           execute a `.wgetrc'-style command

Logging and input file:
  -o,  --output-file=FILE          log messages to FILE
  -a,  --append-output=FILE        append messages to FILE
  -d,  --debug                     print lots of debugging information
  -q,  --quiet                     quiet (no output)
  -v,  --verbose                   be verbose (this is the default)
  -nv, --no-verbose                turn off verboseness, without being quiet
       --report-speed=TYPE         output bandwidth as TYPE.  TYPE can be bits
  -i,  --input-file=FILE           download URLs found in local or external FILE
  

In [ ]:
from csv import reader
#Load data into the notebook
with open('nyc_taxis.csv', 'r') as taxis_file:
  taxis = list(reader(taxis_file))

print(len(taxis))
print(len(taxis[0]))


2014
15


In [ ]:
import numpy as np
np_taxis = np.array(taxis)

In [ ]:
print(np_taxis[:3])
np_taxis.shape

[['pickup_year' 'pickup_month' 'pickup_day' 'pickup_dayofweek'
  'pickup_time' 'pickup_location_code' 'dropoff_location_code'
  'trip_distance' 'trip_length' 'fare_amount' 'fees_amount'
  'tolls_amount' 'tip_amount' 'total_amount' 'payment_type']
 ['2016' '1' '1' '5' '0' '2' '4' '21.00' '2037' '52.00' '0.80' '5.54'
  '11.65' '69.99' '1']
 ['2016' '1' '1' '5' '0' '2' '1' '16.29' '1520' '45.00' '1.30' '0.00'
  '8.00' '54.30' '1']]


(2014, 15)

I'll only work with a subset of the real data — approximately 90,000 yellow taxi trips to and from New York City airports between January and June 2016. This data set includes a 1/50th random sample.
Below is information about selected columns from the dataset:

* pickup_year: the year of the trip
pickup_month: the month of the trip (January is 1, December is 12)
* pickup_day: the day of the month of the trip
* pickup_location_code: the airport or borough where the trip started
* dropoff_location_code: the airport or borough where the trip ended
* trip_distance: the distance of the trip in miles
* trip_length: the length of the trip in seconds
* fare_amount: the base fare of the trip, in dollars
* total_amount: the total amount charged to the passenger, including all fees, tolls and tips

Detailed information on all columns could be found [here](https://s3.amazonaws.com/dq-content/289/nyc_taxi_data_dictionary.md).

In [ ]:
# Load CSV with NumPy
# Access the column by names
np_taxis = np.genfromtxt('nyc_taxis.csv',delimiter=',', names= True)

References:

[NumPy genfromtxt function - API Reference](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html0)

[Tutorial for genfromtxt](https://www.pythonpool.com/numpy-genfromtxt/)


In [ ]:
print(np_taxis.shape)
print(np_taxis[10]['pickup_location_code'])

In [ ]:
z = np.array([1,2])
print(z.shape)

In [ ]:
y = np.array([[1],[2]])
print(y.shape)

In [ ]:
# Access the column by index
np_taxis = np.genfromtxt('nyc_taxis.csv',delimiter=',', skip_header=1)

In [ ]:
print(np_taxis.shape)

In [ ]:
print(np_taxis[10])

In [ ]:
np.set_printoptions(suppress=True)

In [ ]:
print(np_taxis[10])

In [ ]:
print(np_taxis[1])

In [ ]:
# select 'pickup_location_code', 'dropoff_location_code','fare_amount', 'fees_amount'
cols = [5, 6, 9, 10]
print(np_taxis[:,cols])

### Get the Frequency Table of taxis based on the Pickup Location

In [ ]:
print(np.unique(np_taxis[:,6]))

In [ ]:
unique, counts = np.unique(np_taxis[:,6], return_counts=True)
print(unique)
print(counts)

In [ ]:
print(np_taxis[:,-2])

In [ ]:
# elementwise calculation
# Calculate the mph of each trip
trip_distance_miles = np_taxis[:,7]
trip_length_seconds = np_taxis[:,8]

trip_length_hours = trip_length_seconds / 3600 # 3600 seconds is one hour

trip_mph = trip_distance_miles / trip_length_hours
print(trip_mph)

In [ ]:
# Display the Descriptive analysis of the total taxi charge for your trip
total_amount = np_taxis[:,-2]
# measures of central tendency
mean = np.mean(total_amount)
median = np.median(total_amount)
  
# measures of dispersion
min = np.amin(total_amount)
max = np.amax(total_amount)
range = np.ptp(total_amount)
varience = np.var(total_amount)
sd = np.std(total_amount)
  
print("Descriptive analysis")
print("\n")
print("Measures of Central Tendency")
print("Mean =", mean)
print("Median =", median)
print("Measures of Dispersion")
print("Minimum =", min)
print("Maximum =", max)
print("Range =", range)
print("Varience =", varience)
print("Standard Deviation =", sd)